mysite/blog/urls.py
"""URLs for the blog"""
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

mysite/blog/models.py
"""Models for the blog."""
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """Manager for filtering by published."""

    def get_queryset(self):
        """Filter only published posts."""
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    """A user's blog post model."""

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()  # Default, must add this if you add custom one
    published = PublishedManager()  # Only published posts

    tags = TaggableManager()

    class Meta:
        """Meta info"""
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Get the canonical URL. Multiple URLs may display this post,
        but this will be the official one."""
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    """Comment for a blog post."""
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    class Meta:
        ordering = ('created',)

mysite/blog/forms.py
"""Forms for the blog app."""
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    """Form for sharing a post via email."""
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    """Form for inputting comments for posts."""

    class Meta:
        model = Comment
        fields = 'name', 'email', 'body'

mysite/blog/views.py
"""Blogs views"""
from django.db.models import Count
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm
from .models import Post


def post_detail(request, year, month, day, post):
    """Page for an individual blog post."""
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
        id=post.id)
    similar_posts = similar_posts.annotate(some_tags=Count(
        'tags')).order_by('-some_tags', '-publish')[:4]
    return render(request,
                  'blog/post/detail.html',
                  dict(post=post,
                       comments=comments,
                       new_comment=new_comment,
                       comment_form=comment_form,
                       similar_posts=similar_posts))


def post_share(request, post_id):
    """Form for sharing a post."""
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} as {post_url}\n\n {cd['name']}'s " \
                      f"comments: {cd['comments']}"
            send_mail(subject, message, 'admin@mysite.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',
                  dict(post=post,
                       form=form,
                       sent=sent))


def post_list(request, tag_slug=None):
    """Page which lists all published posts."""
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  dict(posts=posts,
                       page=page,
                       tags=tag))

# class PostListView(ListView):
#     """A class based view of the list of blog posts."""
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'

mysite/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog. There are {% total_posts %} posts so far.</p>
    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}
    <h3>Most commented posts</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
      {% for post in most_commented_posts %}
        <li>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
      {% endfor %}
    </ul>
</div>
</body>
</html>

mysite/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} byt {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
    <a href="{% url "blog:post_share" post.id %}">
        Share this post!
    </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {%  empty %}
        There are no similar posts.
    {% endfor %}
{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}


{% for comment in comments %}
    <div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
    <h2>Add a new comment</h2>
    <form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
    </form>
{% endif %}
{% endblock %}

mysite/templates/blog/post/latest_posts.html
<ul>
    {%  for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{  post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{%  block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
        </h2>
        <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {%  endif %}
        {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>Email was sent</h1>
        <p>
            "{{ post.title }}" was sent to {{ form.cleaned_data.to }}.
        </p>
    {%  else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}

mysite/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">
                Previous
            </a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">
                Next
            </a>
        {% endif %}
    </span>
</div>